### ISSUE TITLE
Tải project và thực thi project theo hướng dẫn

### ISSUE THREAD

**Issue by 81Quanghuy** [HNToan7202/video-editing#1]
Link project: https://github.com/HungDo007/video-editing
API : Sử dụng C# và database: MongoDB, Docker
Client:  ReactJs, SASS, Ant Design, web-vitals,...

- [x] Tải project từ dự án 
- [x] #6
- [x] #5

**Comment by 81Quanghuy** [comment]
Lỗi cài đặt server(API): không thể chạy ứng dụng do lỗi kết nối MongoDB

**Comment by HNToan7202** [comment]
Thử xem cài đat theo hướng dẫn [``](https://viblo.asia/p/su-dung-mongodb-trong-aspnet-core-part-2-crud-1VgZvXD95Aw)

**Comment by CongThanh27** [comment]
Lỗi cài đặt máy chủ(API)

**Comment by HNToan7202** [comment]
Không thể chạy đoạn code backend c#

**Comment by CongThanh27** [comment]
Chạy API còn lỗi chưa khắc phục được
