### ISSUE TITLE
Chỉnh sửa lại giao diện Sign up

### ISSUE THREAD

**Issue by 81Quanghuy** [HNToan7202/video-editing#21]
- [x] Tìm hiểu về cách thức hoạt động của trang sign up
- [x] Điều chỉnh lại giao diện dựa trên khung có sẵn của project

**Comment by HNToan7202** [comment]
Ngày 1 :  Tìm hiểu về cách thức hoạt động của trang sign up
Kết quả : 
Link document :

**Comment by HNToan7202** [comment]
Ngày 2 : Điều chỉnh lại giao diện dựa trên khung có sẵn của project
Kết quả : 
Link document :

**Comment by HNToan7202** [comment]
done
