### ISSUE TITLE
Trình bày chi tiết quá trình test case cho chức năng có trong hệ thống

### ISSUE THREAD

**Issue by 81Quanghuy** [HNToan7202/video-editing#29]
- [x] Test case cho chức năng Đăng ký  (Huy)
- [x] Test case cho chức năng Thêm trận đấu (Huy)
- [ ] #32
- [x] Test case cho chức năng Thêm video (Huy) Chèn video  từ gallery khi đang xử lý video
- [ ] #33
- [x] Test case cho chức năng Chia sẻ video (Huy)
- [x] Test case cho chức năng Đăng nhập (Thành) 
- [x] Test case cho chức năng Xóa trận đấu (Thành)
- [x] Test case cho chức năng Upload file json cho trận đấu (Thành)
- [x] Test case cho chức năng Xóa video(hình ảnh) (Thành)
- [x] Test case cho chức năng Download video (Thành)
- [x] #38
- [ ] #34
- [x] #36
- [ ] #35
- [x] #37

**Comment by CongThanh27** [comment]
Done

**Comment by 81Quanghuy** [comment]
[Chi tiết các chức năng đã test của Huy](https://docs.google.com/document/d/1uiJtcniEy9ehCLZBbOMUBBvaxBNw7hcZfmVAWwvGM2U/edit)

**Comment by 81Quanghuy** [comment]
Còn một số chức năng đang bị lỗi nên không thể test được. Nhóm đang trong quá trình nghiêm cứu và fix các lỗi trên

**Comment by CongThanh27** [comment]
Test case cho chức năng Đăng nhập 
`import fs from 'fs';
async function testLogin(browser) {
  await browser.url("http://localhost:3000");
  const username = await browser.$("#login-username");
  await username.setValue("congthanh27");
  await browser.pause(1000);
  const password = await browser.$("#login-password");
  await password.setValue("28072002Thanh@");
  await browser.pause(1000);
  const loginButton = await browser.$("#login-button");
  await loginButton.click();
  await browser.pause(1000);
  await browser.saveScreenshot("./caseLoginuserName.png");
  await browser.pause(1000);
  fs.existsSync("./caseLogin.png");
}
export { testLogin };
import fs from "node:fs";
import { remote } from "webdriverio";
const browser = await remote({
  capabilities: {
    browserName: "chrome",
    "goog:chromeOptions": {
      args: process.env.CI ? ["headless", "disable-gpu"] : [],
    },
  },
});


//Đăng nhập sai username
await browser.url("http://localhost:3000/");
const usernameError = await browser.$("#login-username");
await usernameError.setValue("congthanh28");
await browser.pause(1000);
const passwordError = await browser.$("#login-password");
await passwordError.setValue("28072002Thanh@");
await browser.pause(1000);
const loginButtonError = await browser.$("#login-button");
await loginButtonError.click();
await browser.pause(1000);
await browser.saveScreenshot("./caseLoginFailusername.png");
await browser.pause(1000);
//Load lại trang
await browser.refresh();
//Đăng nhập sai password
await browser.pause(1000);
const usernameError1 = await browser.$("#login-username");
await usernameError1.setValue("congthanh27");
await browser.pause(1000);
const passwordError1 = await browser.$("#login-password");
await passwordError1.setValue("28072002Thanh@1");
await browser.pause(1000);
const showPassword = await browser.$("#login-password-icon");
await showPassword.click();
await browser.pause(1000);
const loginButtonError1 = await browser.$("#login-button");
await loginButtonError1.click();
await browser.pause(1000);
await browser.saveScreenshot("./caseLoginFailpassword.png");
await browser.deleteSession();


// fails if file was not created
fs.existsSync("./caseLogin.png");


import fs from "fs";
async function testlogout(browser) {
  await browser.pause(1000);
  const usernameLogout = await browser.$("#logout-buttun");
  await usernameLogout.click();
  await browser.pause(1000);
  await browser.saveScreenshot("./caseLogout.png");
  await browser.pause(1000);
  //đóng trình duyệt
  await browser.deleteSession();
  fs.existsSync("./caseLogin.png");
}
export{testlogout};`

**Comment by HNToan7202** [comment]
Chi tiết các chức năng đã test của Toàn :
https://docs.google.com/document/d/1EbBG58gy0PTGd0sbZ78KIFpGMdpvJWB_/edit?usp=sharing&ouid=117941689074632474557&rtpof=true&sd=true
