### ISSUE TITLE
Tìm hiểu cấu trúc giao diện của trang web

### ISSUE THREAD

**Issue by 81Quanghuy** [HNToan7202/video-editing#4]
- [x]  1. Tìm hiểu phân tích các thành phần cơ bản của giao diện trang web (Huy)
- [x]  2. Phân tích các thành phần của header, footer, side bar (Thành)
- [x]  3. Phân tích các thành phần của nội dung chính và các phần phụ còn lại. (Toàn )

**Comment by 81Quanghuy** [comment]
Tìm hiểu phân tích các thành phần cơ bản của giao diện trang web: [https://docs.google.com/document/d/1nUa-SGvIxOXt4W4KgtmaKGMvYN7if6KOGOjfHGAhN1A/edit?usp=sharing](url)

**Comment by HNToan7202** [comment]
Phân tích các thành phần của nội dung chính và các phần phụ còn lại : https://docs.google.com/document/d/1WCYDRvQp-NPtRUsNxWJma7f3KtUPBjb6a-4t0zyfCmk/edit?usp=sharing

**Comment by CongThanh27** [comment]
Phân tích các thành phần của header, footer, side bar:
https://docs.google.com/document/d/1LUWKkEynod0YengPs7JyE4_dMapcATSv/edit?usp=sharing&ouid=113775281174867229189&rtpof=true&sd=true
