### ISSUE TITLE
Chạy API của project

### ISSUE THREAD

**Issue by 81Quanghuy** [HNToan7202/video-editing#5]

**Comment by CongThanh27** [comment]
Để chạy API của đồ án cần làm theo các bước sau:

- [ ] Cài đặt .NET Core SDK 5.0 .

- [ ] Cài đặt MongoDB  hoặc sử dụng MongoDB Atlas.

- [ ] Đăng ký tài khoản Cloudinary và lấy API Key, API Secret và Cloud Name .

- [ ] Clone repo từ GitHub: https://github.com/HungDo007/video-editing.

**Tiến hành:**

Mở Terminal và di chuyển đến thư mục đã được tải xuống từ repo.

- [ ] Sử dụng lệnh sau để cài đặt các gói cần thiết cho API: dotnet restore

- [ ] Cấu hình API để sử dụng MongoDB và Cloudinary trong file: appsettings.json

Để chạy API, sử dụng lệnh sau: dotnet run

Khi API đã được chạy, bạn có thể truy cập API qua trình duyệt web.

**Comment by HNToan7202** [comment]
Không xảy ra lỗi
